=== Farreset/Examen-Final-DDL-MO4/DiagramaEx.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
<xsd:element name="Karate" type="tipoClases"/>
<!--Creacion de classes principal-->
<xsd:complexType name="tipoClases">
        <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
                <xsd:sequence>
                    <xsd:element name="Aspirantes" type="typeAspirantes"/>
                    <xsd:element name="Jueces" type="typeJueces"/>
                </xsd:sequence>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>
<!--Aspirantes-->
    <xsd:complexType name="typeAspirantes">
        <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
                <xsd:sequence>
                    <xsd:element name="id_asp" type="codigo"/>
                    <xsd:element name="nom" type="xsd:string"/> 
                    <xsd:element name="ap" type="xsd:string"/>
                    <xsd:element name="DNI" type="codDNI"/>
                    <xsd:element name="tel" type="numTel"/>
                    <xsd:element name="direccion" type="xsd:string"/>
                    <xsd:element name="naciemiento" type="xsd:date"/>
                    <xsd:element name="Dan" type="xsd:string"/>
                    <xsd:element name="cinturon"  type="xsd:string"/>
                    <xsd:element name="Fecha_ingreso_Dan" type="xsd:date"/>
                    <xsd:element name="Foto"  type="xsd:string"/>
                    <xsd:element name="Tiempo_Dan_Anterior" type="xsd:date"/>
                    <xsd:element name="FotoDni" type="xsd:string"/>
                    <xsd:element name="FotoGrados" type="xsd:string"/>
                </xsd:sequence>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

<!--Aspirantes-->
<!--Jueces-->
    <xsd:complexType name="typeJueces">
        <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
                <xsd:sequence>
                    <xsd:element name="id_juez" type="codigo"/>
                    <xsd:element name="nom" type="xsd:string"/> 
                    <xsd:element name="ap" type="xsd:string"/>
                    <xsd:element name="DiplomaJuez" type="boolean"/>
                </xsd:sequence>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

<!--Jueces-->

<!--Creacion de restriciones en los datos-->
<xsd:simpleType name="codigo">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9]{3}"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="codDNI">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9]{7,8}[A-Z]"/>
    </xsd:restriction>
  </xsd:simpleType>
    <xsd:simpleType name="numTel">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9]{9}"/>
    </xsd:restriction>
  </xsd:simpleType>

<xsd:simpleType name="boolean">
  <xsd:restriction base="xsd:boolean">
    <xsd:pattern value="true"/>
    <xsd:pattern value="false"/>
  </xsd:restriction>
</xsd:simpleType>

<!--Creacion de restriciones en los datos-->
</xsd:schema>

=== Farreset/Examen-Final-DDL-MO4/DiagramaEx.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="estiloxml.css"?>
<Karate  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="DiagramaEx.xsd">
    <Aspirantes>     
        <id_asp>001</id_asp>
        <nom>Carles</nom>
        <ap>Puigdemont</ap>
        <DNI>78455623F</DNI>
        <tel>978565565</tel>
        <direccion>C/Valmesque Callis</direccion>
        <naciemiento>1962-12-29</naciemiento>
        <Dan>3r</Dan>
        <cinturon>negro</cinturon>
        <Fecha_ingreso_Dan>1971-03-05</Fecha_ingreso_Dan>
        <Foto>Puixi.png</Foto>
        <Tiempo_Dan_Anterior>1969-03-06</Tiempo_Dan_Anterior>
        <FotoDni>Puixi.png</FotoDni>
        <FotoGrados>Gradomedio.png</FotoGrados>
    </Aspirantes> 
    <Jueces>     
        <id_juez>002</id_juez>
        <nom>Adolfo</nom>
        <ap>Domingez</ap>
        <DiplomaJuez>true</DiplomaJuez>
    </Jueces> 

</Karate>
